enable CLM by default
newrelic/newrelic-ruby-agent pull request #1287
Opened 2022-07-27 04:53 UTC by fallwith

following the successes reported by a good number of opting-in adopters,
the decision has been made to enable code level metrics reporting in the
Ruby agent by default. users may still come up with feature requests for
additional CLM functionality or instrumented library coverage, but the
core functionality in place currently is thought to be stable and ready
for enabling by default.

resolves #1260

2022-07-27 16:51 UTC, kaylareopelle requested changes
Could you make the description in default_source.rb match the description in newrelic.yml?

2022-07-27 18:18 UTC, fallwith commented
> Could you make the description in default_source.rb match the description in newrelic.yml?

Sure thing, addressed with [da6b4b5](https://github.com/newrelic/newrelic-ruby-agent/pull/1287/commits/da6b4b5d7583762741f0eb324c662e32455190a4)

2022-07-27 18:19 UTC, kaylareopelle submitted a review, later dismissed
Thanks for the fix! 🍵

2022-07-28 20:21 UTC, tannalynn approved these changes
💯

2022-07-28 20:37 UTC, merged