Don't modify frozen Logger instance
newrelic/newrelic-ruby-agent pull request #1291
Opened 2022-07-27 21:50 UTC by tannalynn

_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
This PR adds checks for if the logger is frozen before attempting to set/change the `@skip_instrumenting` instance variable. Since this variable is only used internally in the agent and we know those instances of Logger are not frozen, this shouldn't interfere with the purpose of this variable. 
closes #1288

Submitter Checklist:
- [ ] Include a link to the related GitHub issue, if applicable
- [ ] Include a security review link, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

2022-07-27 22:16 UTC, kaylareopelle requested changes
I like where this is headed! Could you add tests for the new guard statements?

2022-07-27 23:03 UTC, fallwith commented on lib/new_relic/agent/instrumentation/logger/instrumentation.rb
> +          return if self.frozen?
These can just be `return if frozen?`

2022-07-27 23:27 UTC, tannalynn commented
> I like where this is headed! Could you add tests for the new guard statements?

Resolved in 134f6e441b1bfd483d3f18308beb65055b947e33

2022-07-27 23:52 UTC, fallwith commented
The instrumentation code has this comment:

```ruby
# It's critical we don't instrument logging from metric recording
# methods within NewRelic::Agent, or we'll stack overflow!!
mark_skip_instrumenting
```

Is being able to apply the mark critical only for the agent's own Logger instances?

If it is only critical for the agent's own Logger instances, then why are we bothering to apply the instance var to any other instances in the first place? We could define a method on only our instances and then have the instrumentation call that method only if it is defined.

If it is critical for other instances, then how can we accomplish the same mark/clear functionality when a logger is frozen? Would we keep an internal hash of Logger instance object ids and their current skip/don't skip status?

2022-07-28 00:05 UTC, kaylareopelle commented
@fallwith  - The instance var is also used in the ActiveSupportLogger instrumentation to prevent double logging.

2022-07-28 00:09 UTC, kaylareopelle approved these changes
Thank you for adding the test! There's one optional suggestion.

2022-07-28 00:09 UTC, kaylareopelle commented on test/multiverse/suites/logger/logger_instrumentation_test.rb
> +    assert !@logger.instance_variable_defined?(:@skip_instrumenting), "instance variable should not be defined"
`refute` would do the same thing as `assert !` here!

2022-07-28 03:05 UTC, fallwith commented
> @fallwith - The instance var is also used in the ActiveSupportLogger instrumentation to prevent double logging.

OK cool, that means that there are indeed some third party loggers that need to be marked for skipping. My concern then is that a frozen logger might need to be marked for skipping too.

There's also no current way to configure the agent to enable instrumentation only for certain logger instances.

Questions...

- Should frozen loggers have their output forwarded or decorated?
    - If so, do we need to develop a mark/unmark system for frozen loggers that doesn't use instance vars?
    - If not, the prepended/chained method could just `yield` early when called by a frozen logger
- Regardless of the logger being frozen or not, should loggers targetting `/dev/null` have their output forwarded or decorated?

Here's my current take:

- The contents of this PR look great and I absolutely think they should be merged in as they are a great improvement over what we currently have
- I'm not yet sure we're ready to have the current contents alone close out #1288

2022-07-29 21:44 UTC, tannalynn commented
> > @fallwith - The instance var is also used in the ActiveSupportLogger instrumentation to prevent double logging.
> 
> OK cool, that means that there are indeed some third party loggers that need to be marked for skipping. My concern then is that a frozen logger might need to be marked for skipping too.
> 
> There's also no current way to configure the agent to enable instrumentation only for certain logger instances.
> 
> Questions...
> 
> * Should frozen loggers have their output forwarded or decorated?
>   
>   * If so, do we need to develop a mark/unmark system for frozen loggers that doesn't use instance vars?
>   * If not, the prepended/chained method could just `yield` early when called by a frozen logger
> * Regardless of the logger being frozen or not, should loggers targetting `/dev/null` have their output forwarded or decorated?
> 
> Here's my current take:
> 
> * The contents of this PR look great and I absolutely think they should be merged in as they are a great improvement over what we currently have
> * I'm not yet sure we're ready to have the current contents alone close out [Can't modify frozen Logger #1288](https://github.com/newrelic/newrelic-ruby-agent/issues/1288)

Thats a good question. I originally thought that we knew that the loggers we would care about would be not frozen, but I'm not as familiar with ActiveSupportLogger. Is that something that just rails uses for itself, or is that something anyone can create and use (and freeze)?  The ActiveSupportLogger instrumentation is only to prevent double logging, correct? So at least if it WAS frozen we wouldn't have issues with recursion (like we would with the agent logger and metrics), but it would double up how many logs we're grabbing which isn't great. 

As for loggers targeting `dev/null`, that's a great question, I'm not sure. I don't remember that coming up during the original logging work (although perhaps @kreopelle might have some thoughts about that).

2022-08-01 19:19 UTC, fallwith commented
After some thought and group discussion, we really ought to get this fix out in the next release. We can revisit alternative non-instance-var based behavior toggles and per-logger-output-destination filtration later with separate issues should they arise beyond the theoretical in future.

2022-08-01 20:39 UTC, merged