CI: slack notification if CI SUCCESS after FAILURE
newrelic/newrelic-ruby-agent pull request #1519
Opened 2022-10-02 03:14 UTC by luigieai

_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Add slack notification when workflow is succeeded when previously workflow have failed state, I implemented [get status of last workflow](https://github.com/marketplace/actions/get-status-of-last-workflow) that uses Github API

Submitter Checklist:
- Should fix https://github.com/newrelic/newrelic-ruby-agent/issues/1397

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

2022-10-02 03:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-ruby-agent?pullRequest=1519) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-ruby-agent?pullRequest=1519) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-ruby-agent?pullRequest=1519) it.</sub>

2022-10-03 07:42 UTC, fallwith requested changes
Hi @luigieai,

Thank you very much for your PR. Making use of the `get-status-of-last-workflow` GitHub Action is a great idea! I think it will solve the problem perfectly.

I have 2 requests for changes to be made:

**Change 1:** When I look at the [Example usage](https://github.com/marketplace/actions/get-status-of-last-workflow#example-usage) section of the documentation page you linked to, it shows the following:

- Setting the last status to a `last_status` object
- Calling `steps.last_status.outputs.last_status` to obtain the last status value and compare it with `'failure'`

When I look at your PR, I see that first item being done, but I don't see the second item being done. I think you are setting the `last_status` object correctly, but I don't see you checking the actual last status value to see if it is equal to `'failure'`.

If you would like any help on this or to discuss it further, please let us know.


**Change 2:** The .yml file is now missing the trailing newline at the very end of the file. You can either set up your text editor to add newlines to the end of YAML (or all) files automatically, or you can just manually create a blank last line. Once you have done so, the little red GitHub warning sign should disappear from the diff view.

2022-10-04 03:59 UTC, luigieai commented
Hello @fallwith Thanks for the review.

I added the missing check (oops :D) and the blank last line, everthing should be fixed, can you please take a look again?

Thanks!

2022-10-04 04:42 UTC, fallwith approved these changes

2022-10-04 04:43 UTC, fallwith commented
Many thanks for your contribution, @luigieai!

2022-10-04 04:43 UTC, merged