Add test for vendors
newrelic/newrelic-ruby-agent pull request #1691
Opened 2022-12-09 19:56 UTC by hannahramadan

Add test to ensure expected and actual `vendors` match. Resolve TODO.

2022-12-09 20:11 UTC, kaylareopelle approved these changes
Kudos for addressing this old TODO! Thanks @tannalynn  for your help!

2022-12-09 20:11 UTC, merged

2022-12-09 20:31 UTC, fallwith requested changes

2022-12-09 20:31 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +          (test_case_attributes['vendors'] || []).each do |k, v|
Would you please explain the need for `|| []`? I want to make sure the TODO is fully satisfied by there always being vendor checks performed.

2022-12-09 20:31 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +              %Q(Wrong "#{k}" #{event_type} attribute; expected #{v.inspect}, was #{actual_attributes[k.to_s].inspect})
It is my understanding that `k` and `v` are always strings for this new test. Is that correct? If so, all of the `to_s` and `#inspect` calls can be removed. Also NOTE that by virtue of using interpolation (`#{}`), Ruby will automatically call `#to_s` on the interpolated object.

2022-12-09 20:31 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +          end
When I run the new test, I see that it there is a `'vendors'` key present only twice.

In those 2 cases, for me `k` is equal to either `'44@nr'`, `'foo'`, or `'bar'`. `v` is always `nil`. The corresponding `actual_attributes[k.to_s]` value is always `nil`. So at least on my machine with a single Ruby version being tested, we're really only ever comparing `nil` with `nil` and getting a false sense of security from it. Am I doing something incorrectly?

My wild guess is that given the `test_case_attributes['vendors']` value of `['foo', 'bar']`, you wanted `k` to end up holding `'foo'` and `v` to end up holding `'bar'`. If that's the case, we'll need to change the iteration syntax.

2022-12-10 02:34 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +          (test_case_attributes['vendors'] || []).each do |k, v|
addressed with https://github.com/newrelic/newrelic-ruby-agent/pull/1692

2022-12-10 02:34 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +              %Q(Wrong "#{k}" #{event_type} attribute; expected #{v.inspect}, was #{actual_attributes[k.to_s].inspect})
addressed with https://github.com/newrelic/newrelic-ruby-agent/pull/1692

2022-12-10 02:34 UTC, fallwith commented on test/new_relic/agent/distributed_tracing/trace_context_cross_agent_test.rb
> +          end
addressed with https://github.com/newrelic/newrelic-ruby-agent/pull/1692