tracks retained objects in memory profiler for Performance tests
newrelic/newrelic-ruby-agent pull request #466
Opened 2020-10-05 15:55 UTC by mwlang

# Overview

To have a repeatable process for tracking and detecting memory leaks, the performance tests were improved to 
track GC.stats[:old_objects] with capability to baseline then compare.  Performance tests were enhanced to
flush stats for old_objects by running major GC sweeps three times, disabling GC during test runs, then re-enabling and running 3 times after the test run.  This ensures consistent tracking and baselining.

The `test/performance/README.md` was also updated for correctness as running the tests while homed to the repo's root folder did not quite work as advertised.  The performance test now also correctly loads the Ruby agent before running whereas before would complain about not finding specific files.

Minor typos, misspellings, etc. were fixed in comments.

2020-10-09 21:56 UTC, rachelleahklein requested changes
Thanks for making this improvement to our performance tests! It will serve us well in preventing memory leaks.

I've requested a few small changes on the documentation side.

2020-10-12 14:25 UTC, mwlang commented on test/performance/README.md
> +$ script/runner
Fair point.  Before I remove, though, and in light of our discussion in retro, if we're automating the performance benchmarking in any way, we probably want to keep this info around, but perhaps elaborate further about capturing results of all tests for comparison purposes?

2020-10-12 14:31 UTC, mwlang commented on test/performance/suites/transaction_tracing.rb
> +  def test_spans_with_custom_attributes
This test was useful to me when I was tracking down possible memory leaks.  By creating spans and setting custom attributes on that span, I was guaranteed the Span's `@attributes` property was allocated.  At the end of the day, it turned out that it was the `test_long_transactions` test that proved most useful overall.

2020-10-12 14:35 UTC, mwlang commented on test/performance/README.md
> +$ script/runner
I just ran `script/runner` and it turns out our thread_profiling test suite has some errors setting up mocha.  It's attempting to use mocha outside context of what it thinks a test environment is.  This is a bug we should fix, but not a bug I introduced with this commit. 

```
FAILED: ThreadProfiling#test_gather_backtraces_subscribed
Mocha::NotInitializedError: Mocha methods cannot be used outside the context of a test
   test/performance/suites/thread_profiling.rb:37:in `block (2 levels) in setup'
```

2020-10-12 15:10 UTC, mwlang commented on test/performance/README.md
> +$ script/runner
This is now solved.  We needed to add `mocha_setup` and `mocha_teardown` to our `setup` and `teardown` methods.  Instructions on how to instrument Cucumber in mocha's README were key to figuring this out.

2020-10-14 18:31 UTC, rachelleahklein commented on test/performance/README.md
> +$ script/runner
Great! Thanks for the fix!

For the record, I'm definitely in favor of a suite of performance tests, hopefully automated, but I think we will need to carefully evaluate the current suite, what's actually useful, and what we'd want to add before making this part of a PR acceptance or release process.

2020-10-15 16:51 UTC, rachelleahklein commented
@mwlang and I are both still running into some errors when trying to run the whole suite locally, so I have requested more research into those issues.

2020-10-15 17:37 UTC, mwlang commented
The entire performance test suite is repaired and now runs w/o error.  However, this PR as-is will still print failing messages on Redis related tests because a separate PR was submitted earlier for Redis instrumentation detection and to avoid conflict merges, that bit was left out of this PR

2020-10-20 17:06 UTC, rachelleahklein approved these changes
The whole suite works for me now. Thanks for all your improvements and troubleshooting.

2020-10-20 17:06 UTC, merged