Deprecate legacy excon instrumentation
newrelic/newrelic-ruby-agent pull request #605
Opened 2021-02-26 19:31 UTC by tannalynn

_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
We discovered prepend was not needed for excon instrumentation. Very old excon versions require method chaining, but we are removing these old versions from support. This PR deprecates the legacy method chaining instrumentation for these older unsupported versions.

# Related Github Issue
closes #582

2021-03-19 15:13 UTC, mwlang requested changes
Is not conforming to our new configuration setup.  Still references the :disable_excon for example.  We need to honor 
```yaml
instrumentation:
  excon: disabled
```
To disable.  Since we're auto-instrumenting via adding to excon's middleware stack, I suggest, "auto" is equivalently the same to "enabled". If "chain" or "prepend" are encountered, we effectively treat this as "enabled" and produced to install middleware accordingly.  (i.e. there's no difference in what happens between these options).  We may want to log a debug message saying as much.)

2021-03-19 18:20 UTC, tannalynn commented
> Is not conforming to our new configuration setup. Still references the :disable_excon for example. We need to honor
> 
> ```yaml
> instrumentation:
>   excon: disabled
> ```
> 
> To disable. Since we're auto-instrumenting via adding to excon's middleware stack, I suggest, "auto" is equivalently the same to "enabled". If "chain" or "prepend" are encountered, we effectively treat this as "enabled" and produced to install middleware accordingly. (i.e. there's no difference in what happens between these options). We may want to log a debug message saying as much.)

Alright, I added a check for the allowed_by_config? method for excon, which should check if it's enabled. I didn't make any other changes since we don't need to check if it's auto/chain/prepend since the behavior is the same for all of those anyways, I believe.

2021-03-24 20:49 UTC, mwlang requested changes
There are not changes to the default_source to add `:'instrumentation.excon'` so it can be enabled/disabled in the new standard way.  Here, `prepend`, `chain` will stand to mean `enabled` and doesn't actually toggle between a prepend or chain method of instrumenting.  My suggestion (and we can discuss this more as a team): just list `[auto|enabled|disabled]` as choices in the description.

2021-03-25 15:00 UTC, mwlang requested changes

2021-03-25 15:00 UTC, mwlang commented on lib/new_relic/agent/instrumentation/excon.rb
> +    Deprecator.deprecate :install_legacy_excon_instrumentation, :install_middleware_excon_instrumentation, "8.0.0"
I'm not sure how this is working!  I just discovered the same on the prepend_mongo branch required the full namespace: `NewRelic::Agent::Deprecator.deprecate(...)`

2021-04-01 17:43 UTC, mwlang approved these changes
This looks good.  A couple of failing jobs in CI completely unrelated to Excon, so moving forward with merging.

2021-04-01 17:43 UTC, merged