Updated Contributing Guide
newrelic/newrelic-ruby-agent pull request #666
Opened 2021-05-10 14:43 UTC by ChaelCodes

# Overview
Added a short setup guide to the ruby agent contributing guide to give people an idea of how to set it up. If we want to update these instructions or expand them, please let me know. I had to make these up, because there weren't any install instructions that I could find in the README, Contrib guide, or the Ruby Agent documentation site.

Also fixed broken link.

# Related Github Issue
Include a link to the related GitHub issue, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

2021-05-11 17:28 UTC, angelatan2 requested changes

2021-05-11 17:28 UTC, angelatan2 commented on CONTRIBUTING.md
> +
Hello @ChaelCodes,  just a couple of things:
1) Please reword Dev on the title to Development
2) Thanks for adding the bulleted list of steps.  Could you remove the last sentence "If you have any issues setting up the repository, let us know in issues."  There is a link at the end for support.  Typically, when developers run into issues, they comment directly in their respective issues.

2021-05-11 17:28 UTC, angelatan2 commented on CONTRIBUTING.md
> +application environments (e.g. Rails, Sinatra, roll-your-own, etc.) See [Ruby agent requirements and supported frameworks](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/ruby-agent-
Looks good.

2021-05-24 14:27 UTC, ChaelCodes commented on CONTRIBUTING.md
> +    - Use rbenv or rvm to install any version of Ruby (2.7.2 recommended)
Updated.

2021-05-24 19:20 UTC, angelatan2 approved these changes
Looks good.  Thank you for contributing to the Ruby Agent!

2021-05-24 19:20 UTC, merged