Kh.expand config file generation to improve documentation
newrelic/newrelic-ruby-agent pull request #724
Opened 2021-07-12 21:59 UTC by wyhaines

# Overview
This PR addresses issue #684. We used the current documentation for the *newrelic.yml* file on the New Relic website, and inserted all of the non-deprecated configuration options, alphabetized, with documentation, into the config file template.

`newrelic install` will now install a *Devise* style, well-documentated configuration file.

# Related Github Issue
#684 

# Testing
We confirmed that the generated config file has all of the same uncommented sections that the old, much shorter version has. So there should be no operational effect to using this longer version.

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

2021-07-13 09:17 UTC, wyhaines commented
That spec failure looks like it is unrelated to the PR. Is that correct?

2021-07-13 17:24 UTC, tannalynn commented
> That spec failure looks like it is unrelated to the PR. Is that correct?

Yes, that's correct. The infinite tracing tests are a bit flaky due to some multithreading issues with our fake trace observer we use for those tests. It's been improved over time, but sometimes it still causes some issues. I've started a rerun on those jobs, but it looks like github actions is having some issues setting up our test environments right now. I'll try again in a bit.

2021-07-13 18:14 UTC, tannalynn requested changes
Thanks so much for working on this one!

The (Dynamic) thing in the docs on some config options default value indicates that the agent decides what the value will be once it starts up (this is for various reasons, depending on the specific config option). For all config options that have that, it might be good to change the example value to something the user would be able to use if uncommented maybe? I mentioned the instrumentation ones in another comment, which is most of them, but the others have various possibilities. Some are simply booleans, so that should be easy to change, some have the options listed in the description (like `slow_sql.record_sql` for example). If you aren't sure about a specific one, just let me know and I'd be happy to help figure out what a good example value to set would be.

2021-07-13 19:40 UTC, creaturenex commented on newrelic.yml
> +# instrumentation.bunny: (Dynamic)
Hello Tanna,

Not a problem, you make a good point.

2021-07-13 19:40 UTC, creaturenex commented on newrelic.yml
> +# entity_guid: nil
ill update that

2021-09-01 16:40 UTC, creaturenex commented
@wyhaines @tannalynn 
I have updated all references to Dynamic. Please review them to see if my default values makes sense for each setting. I am happy to explain my thought process for any of them. Let me know what you think.

2021-09-03 19:16 UTC, tannalynn approved these changes
Looks great! Thank you for getting those Dynamic values updated!

2021-09-03 19:17 UTC, merged